### ISSUE TITLE
Outdated repo description

### ISSUE THREAD

**Issue by AlekSi** [go-devroom/cfp#5]
![image](https://user-images.githubusercontent.com/11512/145784386-10c69fcb-2373-4503-89d7-cbeadfa5310b.png)

It should say 2022 in repository description, not 2021.

**Comment by meyskens** [comment]
Not sure what happened... I changed this yesterday :/ Changed it again :)

**Comment by AlekSi** [comment]
Can confirm! :) Thank you.
